version: '3.8'

services:
  db:
    image: mysql:8.0                      # MySQL 이미지 (필수, 버전은 변경 가능)
    container_name: mysql-container        # 컨테이너 이름 (필수, 변경 가능)
    restart: always                       # 컨테이너 재시작 정책 (권장, 변경 가능)
    ports:
      - "3307:3306"                       # 로컬과 컨테이너 간 포트 매핑 (필수, 필요시 변경 가능)
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword   # MySQL 루트 비밀번호 (필수, 임의로 수정 가능)
      MYSQL_DATABASE: redis_prac_db          # 초기 생성할 데이터베이스 이름 (필수, 임의로 수정 가능)
      MYSQL_USER: user                  # MySQL 일반 사용자 (필수, 임의로 수정 가능)
      MYSQL_PASSWORD: password          # 일반 사용자 비밀번호 (필수, 임의로 수정 가능)
      TZ: Asia/Seoul                      # 서버 시간대 설정
    command:
      - --character-set-server=utf8mb4    # 서버 문자 집합 설정
      - --collation-server=utf8mb4_0900_ai_ci # 기본 정렬 방식 설정
    volumes:
      - ./data/mysql:/var/lib/mysql

  flyway:
    image: flyway/flyway:9.0.0
    container_name: flyway-container
    depends_on:
      - db
    command: [
      "-url=jdbc:mysql://db:3306/redis_prac_db",
      "-user=user",
      "-password=password",
      "migrate"
    ]
    volumes:
      - ./db/migration:/flyway/sql

  redis:
    image: redis:6.2        # Redis 이미지 (최신 안정 버전 선택)
    container_name: redis-container
    restart: always
    ports:
      - "6379:6379"         # Redis 기본 포트
    volumes:
      - ./data/redis:/data  # Redis 데이터 볼륨
    command: redis-server --save 60 1 --loglevel warning